### ISSUE TITLE
Cloning workspaces broken

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSBv2#777]
It gets stuck spinning...
<img width="1655" alt="Screenshot 2023-07-14 at 10 33 21" src="https://github.com/OpenSourceBrain/OSBv2/assets/1556687/c2695e60-8a1f-4b4b-b46e-195b67322d80">

**Comment by filippomc** [comment]
just fixed on dev

**Comment by filippomc** [comment]
fixed on live

**Comment by sanjayankur31** [comment]
@filippomc : it still seems to be happening here. Was the fix deployed on live?

![image](https://github.com/OpenSourceBrain/OSBv2/assets/102575/0e5f58a5-3f90-4255-9859-601a1caacb6c)

**Comment by filippomc** [comment]
yes the fix is deployed and it's the same image that's on dev.. something weird is happening during the clone save

**Comment by sanjayankur31** [comment]
I think I'm still seeing this on live. It's just hanging there. Any idea what's going on @filippomc ?

**Comment by sanjayankur31** [comment]
Also looks broken on dev btw:

![image](https://github.com/OpenSourceBrain/OSBv2/assets/102575/2efd719a-245b-4b65-991d-2bc58a4df714)

**Comment by sanjayankur31** [comment]
```
`(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n(psycopg2.ProgrammingError) can't adapt type 'dict'\n[SQL: UPDATE "Workspaceresource" SET origin=%(origin)s WHERE "Workspaceresource".id = %(Workspaceresource_id)s]\n[parameters: ({'origin': {'path': 'notebook.ipynb'}, 'Workspaceresource_id': 547}, {'origin': {'path': 'Untitled.ipynb'}, 'Workspaceresource_id': 548}, {'origin': {'path': 'simao2/0.220805.1724/sub-10204987456540150313/sub-10204987456540150313_ses-20220310T113527_ophys.nwb'}, 'Workspaceresource_id': 549}, {'origin': {'path': '.ipynb_checkpoints/notebook-checkpoint.ipynb'}, 'Workspaceresource_id': 550}, {'origin': {'path': '.ipynb_checkpoints/Untitled-checkpoint.ipynb'}, 'Workspaceresource_id': 551})]\n(Background on this error at: https://sqlalche.me/e/14/f405)`
```

**Comment by filippomc** [comment]
ok it looks like the autoflush is getting in the way in random occasions. Thanks for the help @sanjayankur31, will fix it as soon as possible

**Comment by filippomc** [comment]
Fixed on live
